name: Linting (Push)

on:
  push:

jobs:
  lint_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9  # Change this to the Python version you are using, e.g., 3.6, 3.7, 3.8, etc.

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      - name: Lint Python code
        run: flake8 --max-line-length=100 --count --ignore=E501,E371,W503,E241,E203,F401,F403 --show-source --statistics
